import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";

const roboto_condensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata = {
  title: "Helpende Handen work",
  description: "Generated by Helpende Handen work",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Helpende Handen work</title>
        <link rel="icon" type="image/x-icon" href="./assets/img/bol_groot.png" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="./assets/css/style.css" />
      </head>
      <body className={roboto_condensed.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
